/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stgad
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ViewName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        BottomMenuPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        InitMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        ClientView = new javax.swing.JMenu();
        ClientMenu = new javax.swing.JMenuItem();
        TrainerView = new javax.swing.JMenu();
        TrainerMenu = new javax.swing.JMenuItem();
        ActivitieView = new javax.swing.JMenu();
        ActivitiesMenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewName.setText("PlaceholderShit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ViewName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ViewName)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DataTable);

        javax.swing.GroupLayout BottomMenuPanelLayout = new javax.swing.GroupLayout(BottomMenuPanel);
        BottomMenuPanel.setLayout(BottomMenuPanelLayout);
        BottomMenuPanelLayout.setHorizontalGroup(
            BottomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BottomMenuPanelLayout.setVerticalGroup(
            BottomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(BottomMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        InitMenu.setText("Init");
        InitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitMenuActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Init");
        InitMenu.add(jMenuItem5);

        jMenuBar1.add(InitMenu);

        ClientView.setText("Clients");

        ClientMenu.setText("ClientManager");
        ClientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientMenuActionPerformed(evt);
            }
        });
        ClientView.add(ClientMenu);

        jMenuBar1.add(ClientView);

        TrainerView.setText("Trainers");

        TrainerMenu.setText("TrainerManager");
        TrainerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerMenuActionPerformed(evt);
            }
        });
        TrainerView.add(TrainerMenu);

        jMenuBar1.add(TrainerView);

        ActivitieView.setText("Activities");

        ActivitiesMenu.setText("ActivitiesManager");
        ActivitiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivitiesMenuActionPerformed(evt);
            }
        });
        ActivitieView.add(ActivitiesMenu);

        jMenuBar1.add(ActivitieView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TrainerMenuActionPerformed

    private void ActivitiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivitiesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActivitiesMenuActionPerformed

    private void ClientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientMenuActionPerformed

    private void InitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InitMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu ActivitieView;
    public javax.swing.JMenuItem ActivitiesMenu;
    public javax.swing.JPanel BottomMenuPanel;
    private javax.swing.JMenuItem ClientMenu;
    public javax.swing.JMenu ClientView;
    public javax.swing.JTable DataTable;
    public javax.swing.JMenu InitMenu;
    public javax.swing.JMenuItem TrainerMenu;
    public javax.swing.JMenu TrainerView;
    public javax.swing.JLabel ViewName;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public void setViewName(String name) {
        ViewName.setText(name);
    }

    public void setTableData(String[] columnNames, Object[][] data) {
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        DataTable.setModel(model);
    }

    public void addClientMenuListener(java.awt.event.ActionListener al) {
        ClientMenu.setActionCommand("ShowClients");
        ClientMenu.addActionListener(al);
    }

    public void addTrainerMenuListener(java.awt.event.ActionListener al) {
        TrainerMenu.setActionCommand("ShowTrainers");
        TrainerMenu.addActionListener(al);
    }

    public void addActivitiesMenuListener(java.awt.event.ActionListener al) {
        ActivitiesMenu.setActionCommand("ShowActivities");
        ActivitiesMenu.addActionListener(al);
    }

    public void addInitMenuListener(java.awt.event.ActionListener al) {
        jMenuItem5.setActionCommand("ShowInit");
        jMenuItem5.addActionListener(al);
    }
}

// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
//  */
// package Views;

// /**
//  *
//  * @author stgad
//  */
// public class MainWindow extends javax.swing.JFrame {

//     /**
//      * Creates new form MainWindow
//      */
//     public MainWindow() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jMenuItem1 = new javax.swing.JMenuItem();
//         jPanel1 = new javax.swing.JPanel();
//         jPanel2 = new javax.swing.JPanel();
//         ViewName = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         DataTable = new javax.swing.JTable();
//         BottomMenuPanel = new javax.swing.JPanel();
//         jMenuBar1 = new javax.swing.JMenuBar();
//         InitMenu = new javax.swing.JMenu();
//         jMenuItem5 = new javax.swing.JMenuItem();
//         ClientView = new javax.swing.JMenu();
//         ClientMenu = new javax.swing.JMenuItem();
//         TrainerView = new javax.swing.JMenu();
//         TrainerMenu = new javax.swing.JMenuItem();
//         ActivitieView = new javax.swing.JMenu();
//         ActivitiesMenu = new javax.swing.JMenuItem();

//         jMenuItem1.setText("jMenuItem1");

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//         ViewName.setText("PlaceholderShit");

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(21, 21, 21)
//                 .addComponent(ViewName)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(17, 17, 17)
//                 .addComponent(ViewName)
//                 .addContainerGap(30, Short.MAX_VALUE))
//         );

//         DataTable.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null}
//             },
//             new String [] {
//                 "Title 1", "Title 2", "Title 3", "Title 4"
//             }
//         ));
//         jScrollPane1.setViewportView(DataTable);

//         javax.swing.GroupLayout BottomMenuPanelLayout = new javax.swing.GroupLayout(BottomMenuPanel);
//         BottomMenuPanel.setLayout(BottomMenuPanelLayout);
//         BottomMenuPanelLayout.setHorizontalGroup(
//             BottomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 0, Short.MAX_VALUE)
//         );
//         BottomMenuPanelLayout.setVerticalGroup(
//             BottomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGap(0, 60, Short.MAX_VALUE)
//         );

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//             .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
//             .addComponent(BottomMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(BottomMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(0, 0, Short.MAX_VALUE))
//         );

//         InitMenu.setText("Init");
//         InitMenu.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 InitMenuActionPerformed(evt);
//             }
//         });

//         jMenuItem5.setText("Init");
//         InitMenu.add(jMenuItem5);

//         jMenuBar1.add(InitMenu);

//         ClientView.setText("Clients");

//         ClientMenu.setText("ClientManager");
//         ClientMenu.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 ClientMenuActionPerformed(evt);
//             }
//         });
//         ClientView.add(ClientMenu);

//         jMenuBar1.add(ClientView);

//         TrainerView.setText("Trainers");

//         TrainerMenu.setText("TrainerManager");
//         TrainerMenu.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 TrainerMenuActionPerformed(evt);
//             }
//         });
//         TrainerView.add(TrainerMenu);

//         jMenuBar1.add(TrainerView);

//         ActivitieView.setText("Activities");

//         ActivitiesMenu.setText("ActivitiesManager");
//         ActivitiesMenu.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 ActivitiesMenuActionPerformed(evt);
//             }
//         });
//         ActivitieView.add(ActivitiesMenu);

//         jMenuBar1.add(ActivitieView);

//         setJMenuBar(jMenuBar1);

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );

//         pack();
//     }// </editor-fold>//GEN-END:initComponents

//     private void TrainerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerMenuActionPerformed
//         // TODO add your handling code here:
        
//     }//GEN-LAST:event_TrainerMenuActionPerformed

//     private void ActivitiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivitiesMenuActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_ActivitiesMenuActionPerformed

//     private void ClientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_ClientMenuActionPerformed

//     private void InitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitMenuActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_InitMenuActionPerformed

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new MainWindow().setVisible(true);
//             }
//         });
//     }

//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     public javax.swing.JMenu ActivitieView;
//     public javax.swing.JMenuItem ActivitiesMenu;
//     public javax.swing.JPanel BottomMenuPanel;
//     private javax.swing.JMenuItem ClientMenu;
//     public javax.swing.JMenu ClientView;
//     public javax.swing.JTable DataTable;
//     public javax.swing.JMenu InitMenu;
//     public javax.swing.JMenuItem TrainerMenu;
//     public javax.swing.JMenu TrainerView;
//     public javax.swing.JLabel ViewName;
//     public javax.swing.JMenuBar jMenuBar1;
//     private javax.swing.JMenuItem jMenuItem1;
//     private javax.swing.JMenuItem jMenuItem5;
//     private javax.swing.JPanel jPanel1;
//     public javax.swing.JPanel jPanel2;
//     private javax.swing.JScrollPane jScrollPane1;
//     // End of variables declaration//GEN-END:variables
// }
